# Generated by Django 5.2 on 2025-05-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
